//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobileOrder.MobileSellReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImportDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportData_OfficeBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportDataSelectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportOnlyOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadZipFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback Import_wfOperationCompleted;
        
        private System.Threading.SendOrPostCallback Import_wfsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Import_KUBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Export_wfOperationCompleted;
        
        private System.Threading.SendOrPostCallback Export_wfsOperationCompleted;
        
        private System.Threading.SendOrPostCallback IE_ImportOnlyOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback FromPPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ToPPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExoprtToWorkFlowOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://192.168.0.10:77/mobilesell/mobilesell.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImportDataCompletedEventHandler ImportDataCompleted;
        
        /// <remarks/>
        public event ExportDataCompletedEventHandler ExportDataCompleted;
        
        /// <remarks/>
        public event ExportData_OfficeBoxCompletedEventHandler ExportData_OfficeBoxCompleted;
        
        /// <remarks/>
        public event ExportDataSelectionCompletedEventHandler ExportDataSelectionCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event DownloadFileCompletedEventHandler DownloadFileCompleted;
        
        /// <remarks/>
        public event ImportOnlyOrdersCompletedEventHandler ImportOnlyOrdersCompleted;
        
        /// <remarks/>
        public event UploadZipFileCompletedEventHandler UploadZipFileCompleted;
        
        /// <remarks/>
        public event Import_wfCompletedEventHandler Import_wfCompleted;
        
        /// <remarks/>
        public event Import_wfsCompletedEventHandler Import_wfsCompleted;
        
        /// <remarks/>
        public event Import_KUBCompletedEventHandler Import_KUBCompleted;
        
        /// <remarks/>
        public event Export_wfCompletedEventHandler Export_wfCompleted;
        
        /// <remarks/>
        public event Export_wfsCompletedEventHandler Export_wfsCompleted;
        
        /// <remarks/>
        public event IE_ImportOnlyOrdersCompletedEventHandler IE_ImportOnlyOrdersCompleted;
        
        /// <remarks/>
        public event FromPPCCompletedEventHandler FromPPCCompleted;
        
        /// <remarks/>
        public event ToPPCCompletedEventHandler ToPPCCompleted;
        
        /// <remarks/>
        public event ExoprtToWorkFlowCompletedEventHandler ExoprtToWorkFlowCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportData(int object_id) {
            object[] results = this.Invoke("ImportData", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportDataAsync(int object_id) {
            this.ImportDataAsync(object_id, null);
        }
        
        /// <remarks/>
        public void ImportDataAsync(int object_id, object userState) {
            if ((this.ImportDataOperationCompleted == null)) {
                this.ImportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportDataOperationCompleted);
            }
            this.InvokeAsync("ImportData", new object[] {
                        object_id}, this.ImportDataOperationCompleted, userState);
        }
        
        private void OnImportDataOperationCompleted(object arg) {
            if ((this.ImportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportDataCompleted(this, new ImportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExportData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExportData(int object_id) {
            object[] results = this.Invoke("ExportData", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExportDataAsync(int object_id) {
            this.ExportDataAsync(object_id, null);
        }
        
        /// <remarks/>
        public void ExportDataAsync(int object_id, object userState) {
            if ((this.ExportDataOperationCompleted == null)) {
                this.ExportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportDataOperationCompleted);
            }
            this.InvokeAsync("ExportData", new object[] {
                        object_id}, this.ExportDataOperationCompleted, userState);
        }
        
        private void OnExportDataOperationCompleted(object arg) {
            if ((this.ExportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportDataCompleted(this, new ExportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExportData_OfficeBox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExportData_OfficeBox(int object_id) {
            object[] results = this.Invoke("ExportData_OfficeBox", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExportData_OfficeBoxAsync(int object_id) {
            this.ExportData_OfficeBoxAsync(object_id, null);
        }
        
        /// <remarks/>
        public void ExportData_OfficeBoxAsync(int object_id, object userState) {
            if ((this.ExportData_OfficeBoxOperationCompleted == null)) {
                this.ExportData_OfficeBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportData_OfficeBoxOperationCompleted);
            }
            this.InvokeAsync("ExportData_OfficeBox", new object[] {
                        object_id}, this.ExportData_OfficeBoxOperationCompleted, userState);
        }
        
        private void OnExportData_OfficeBoxOperationCompleted(object arg) {
            if ((this.ExportData_OfficeBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportData_OfficeBoxCompleted(this, new ExportData_OfficeBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExportDataSelection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExportDataSelection(int[] object_id) {
            object[] results = this.Invoke("ExportDataSelection", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExportDataSelectionAsync(int[] object_id) {
            this.ExportDataSelectionAsync(object_id, null);
        }
        
        /// <remarks/>
        public void ExportDataSelectionAsync(int[] object_id, object userState) {
            if ((this.ExportDataSelectionOperationCompleted == null)) {
                this.ExportDataSelectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportDataSelectionOperationCompleted);
            }
            this.InvokeAsync("ExportDataSelection", new object[] {
                        object_id}, this.ExportDataSelectionOperationCompleted, userState);
        }
        
        private void OnExportDataSelectionOperationCompleted(object arg) {
            if ((this.ExportDataSelectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportDataSelectionCompleted(this, new ExportDataSelectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFile(string content, int object_id, string filename) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        content,
                        object_id,
                        filename});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(string content, int object_id, string filename) {
            this.UploadFileAsync(content, object_id, filename, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(string content, int object_id, string filename, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        content,
                        object_id,
                        filename}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownloadFile(int object_id, string filename) {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        object_id,
                        filename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadFileAsync(int object_id, string filename) {
            this.DownloadFileAsync(object_id, filename, null);
        }
        
        /// <remarks/>
        public void DownloadFileAsync(int object_id, string filename, object userState) {
            if ((this.DownloadFileOperationCompleted == null)) {
                this.DownloadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadFileOperationCompleted);
            }
            this.InvokeAsync("DownloadFile", new object[] {
                        object_id,
                        filename}, this.DownloadFileOperationCompleted, userState);
        }
        
        private void OnDownloadFileOperationCompleted(object arg) {
            if ((this.DownloadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadFileCompleted(this, new DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportOnlyOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ImportOnlyOrders(int[] object_id) {
            object[] results = this.Invoke("ImportOnlyOrders", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ImportOnlyOrdersAsync(int[] object_id) {
            this.ImportOnlyOrdersAsync(object_id, null);
        }
        
        /// <remarks/>
        public void ImportOnlyOrdersAsync(int[] object_id, object userState) {
            if ((this.ImportOnlyOrdersOperationCompleted == null)) {
                this.ImportOnlyOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportOnlyOrdersOperationCompleted);
            }
            this.InvokeAsync("ImportOnlyOrders", new object[] {
                        object_id}, this.ImportOnlyOrdersOperationCompleted, userState);
        }
        
        private void OnImportOnlyOrdersOperationCompleted(object arg) {
            if ((this.ImportOnlyOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportOnlyOrdersCompleted(this, new ImportOnlyOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadZipFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadZipFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content, string filename) {
            object[] results = this.Invoke("UploadZipFile", new object[] {
                        content,
                        filename});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadZipFileAsync(byte[] content, string filename) {
            this.UploadZipFileAsync(content, filename, null);
        }
        
        /// <remarks/>
        public void UploadZipFileAsync(byte[] content, string filename, object userState) {
            if ((this.UploadZipFileOperationCompleted == null)) {
                this.UploadZipFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadZipFileOperationCompleted);
            }
            this.InvokeAsync("UploadZipFile", new object[] {
                        content,
                        filename}, this.UploadZipFileOperationCompleted, userState);
        }
        
        private void OnUploadZipFileOperationCompleted(object arg) {
            if ((this.UploadZipFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadZipFileCompleted(this, new UploadZipFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Import_wf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Import_wf(int[] object_id) {
            object[] results = this.Invoke("Import_wf", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Import_wfAsync(int[] object_id) {
            this.Import_wfAsync(object_id, null);
        }
        
        /// <remarks/>
        public void Import_wfAsync(int[] object_id, object userState) {
            if ((this.Import_wfOperationCompleted == null)) {
                this.Import_wfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImport_wfOperationCompleted);
            }
            this.InvokeAsync("Import_wf", new object[] {
                        object_id}, this.Import_wfOperationCompleted, userState);
        }
        
        private void OnImport_wfOperationCompleted(object arg) {
            if ((this.Import_wfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Import_wfCompleted(this, new Import_wfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Import_wfs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Import_wfs(int object_id) {
            object[] results = this.Invoke("Import_wfs", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Import_wfsAsync(int object_id) {
            this.Import_wfsAsync(object_id, null);
        }
        
        /// <remarks/>
        public void Import_wfsAsync(int object_id, object userState) {
            if ((this.Import_wfsOperationCompleted == null)) {
                this.Import_wfsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImport_wfsOperationCompleted);
            }
            this.InvokeAsync("Import_wfs", new object[] {
                        object_id}, this.Import_wfsOperationCompleted, userState);
        }
        
        private void OnImport_wfsOperationCompleted(object arg) {
            if ((this.Import_wfsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Import_wfsCompleted(this, new Import_wfsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Import_KUB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Import_KUB(int object_id) {
            object[] results = this.Invoke("Import_KUB", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Import_KUBAsync(int object_id) {
            this.Import_KUBAsync(object_id, null);
        }
        
        /// <remarks/>
        public void Import_KUBAsync(int object_id, object userState) {
            if ((this.Import_KUBOperationCompleted == null)) {
                this.Import_KUBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImport_KUBOperationCompleted);
            }
            this.InvokeAsync("Import_KUB", new object[] {
                        object_id}, this.Import_KUBOperationCompleted, userState);
        }
        
        private void OnImport_KUBOperationCompleted(object arg) {
            if ((this.Import_KUBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Import_KUBCompleted(this, new Import_KUBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Export_wf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Export_wf(int[] object_id) {
            object[] results = this.Invoke("Export_wf", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Export_wfAsync(int[] object_id) {
            this.Export_wfAsync(object_id, null);
        }
        
        /// <remarks/>
        public void Export_wfAsync(int[] object_id, object userState) {
            if ((this.Export_wfOperationCompleted == null)) {
                this.Export_wfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExport_wfOperationCompleted);
            }
            this.InvokeAsync("Export_wf", new object[] {
                        object_id}, this.Export_wfOperationCompleted, userState);
        }
        
        private void OnExport_wfOperationCompleted(object arg) {
            if ((this.Export_wfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Export_wfCompleted(this, new Export_wfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Export_wfs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Export_wfs(int object_id) {
            object[] results = this.Invoke("Export_wfs", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Export_wfsAsync(int object_id) {
            this.Export_wfsAsync(object_id, null);
        }
        
        /// <remarks/>
        public void Export_wfsAsync(int object_id, object userState) {
            if ((this.Export_wfsOperationCompleted == null)) {
                this.Export_wfsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExport_wfsOperationCompleted);
            }
            this.InvokeAsync("Export_wfs", new object[] {
                        object_id}, this.Export_wfsOperationCompleted, userState);
        }
        
        private void OnExport_wfsOperationCompleted(object arg) {
            if ((this.Export_wfsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Export_wfsCompleted(this, new Export_wfsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IE_ImportOnlyOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int IE_ImportOnlyOrders(int object_id) {
            object[] results = this.Invoke("IE_ImportOnlyOrders", new object[] {
                        object_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IE_ImportOnlyOrdersAsync(int object_id) {
            this.IE_ImportOnlyOrdersAsync(object_id, null);
        }
        
        /// <remarks/>
        public void IE_ImportOnlyOrdersAsync(int object_id, object userState) {
            if ((this.IE_ImportOnlyOrdersOperationCompleted == null)) {
                this.IE_ImportOnlyOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIE_ImportOnlyOrdersOperationCompleted);
            }
            this.InvokeAsync("IE_ImportOnlyOrders", new object[] {
                        object_id}, this.IE_ImportOnlyOrdersOperationCompleted, userState);
        }
        
        private void OnIE_ImportOnlyOrdersOperationCompleted(object arg) {
            if ((this.IE_ImportOnlyOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IE_ImportOnlyOrdersCompleted(this, new IE_ImportOnlyOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FromPPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FromPPC([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content, string filename, int object_id) {
            object[] results = this.Invoke("FromPPC", new object[] {
                        content,
                        filename,
                        object_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FromPPCAsync(byte[] content, string filename, int object_id) {
            this.FromPPCAsync(content, filename, object_id, null);
        }
        
        /// <remarks/>
        public void FromPPCAsync(byte[] content, string filename, int object_id, object userState) {
            if ((this.FromPPCOperationCompleted == null)) {
                this.FromPPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFromPPCOperationCompleted);
            }
            this.InvokeAsync("FromPPC", new object[] {
                        content,
                        filename,
                        object_id}, this.FromPPCOperationCompleted, userState);
        }
        
        private void OnFromPPCOperationCompleted(object arg) {
            if ((this.FromPPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FromPPCCompleted(this, new FromPPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ToPPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public byte[][] ToPPC(string filename, int object_id) {
            object[] results = this.Invoke("ToPPC", new object[] {
                        filename,
                        object_id});
            return ((byte[][])(results[0]));
        }
        
        /// <remarks/>
        public void ToPPCAsync(string filename, int object_id) {
            this.ToPPCAsync(filename, object_id, null);
        }
        
        /// <remarks/>
        public void ToPPCAsync(string filename, int object_id, object userState) {
            if ((this.ToPPCOperationCompleted == null)) {
                this.ToPPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnToPPCOperationCompleted);
            }
            this.InvokeAsync("ToPPC", new object[] {
                        filename,
                        object_id}, this.ToPPCOperationCompleted, userState);
        }
        
        private void OnToPPCOperationCompleted(object arg) {
            if ((this.ToPPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ToPPCCompleted(this, new ToPPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExoprtToWorkFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExoprtToWorkFlow(string pd1, string pd2, int object_id) {
            object[] results = this.Invoke("ExoprtToWorkFlow", new object[] {
                        pd1,
                        pd2,
                        object_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExoprtToWorkFlowAsync(string pd1, string pd2, int object_id) {
            this.ExoprtToWorkFlowAsync(pd1, pd2, object_id, null);
        }
        
        /// <remarks/>
        public void ExoprtToWorkFlowAsync(string pd1, string pd2, int object_id, object userState) {
            if ((this.ExoprtToWorkFlowOperationCompleted == null)) {
                this.ExoprtToWorkFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExoprtToWorkFlowOperationCompleted);
            }
            this.InvokeAsync("ExoprtToWorkFlow", new object[] {
                        pd1,
                        pd2,
                        object_id}, this.ExoprtToWorkFlowOperationCompleted, userState);
        }
        
        private void OnExoprtToWorkFlowOperationCompleted(object arg) {
            if ((this.ExoprtToWorkFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExoprtToWorkFlowCompleted(this, new ExoprtToWorkFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ImportDataCompletedEventHandler(object sender, ImportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExportDataCompletedEventHandler(object sender, ExportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExportData_OfficeBoxCompletedEventHandler(object sender, ExportData_OfficeBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportData_OfficeBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportData_OfficeBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExportDataSelectionCompletedEventHandler(object sender, ExportDataSelectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportDataSelectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportDataSelectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DownloadFileCompletedEventHandler(object sender, DownloadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ImportOnlyOrdersCompletedEventHandler(object sender, ImportOnlyOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportOnlyOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportOnlyOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UploadZipFileCompletedEventHandler(object sender, UploadZipFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadZipFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadZipFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Import_wfCompletedEventHandler(object sender, Import_wfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Import_wfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Import_wfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Import_wfsCompletedEventHandler(object sender, Import_wfsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Import_wfsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Import_wfsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Import_KUBCompletedEventHandler(object sender, Import_KUBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Import_KUBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Import_KUBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Export_wfCompletedEventHandler(object sender, Export_wfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Export_wfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Export_wfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Export_wfsCompletedEventHandler(object sender, Export_wfsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Export_wfsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Export_wfsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void IE_ImportOnlyOrdersCompletedEventHandler(object sender, IE_ImportOnlyOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IE_ImportOnlyOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IE_ImportOnlyOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void FromPPCCompletedEventHandler(object sender, FromPPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FromPPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FromPPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ToPPCCompletedEventHandler(object sender, ToPPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ToPPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ToPPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExoprtToWorkFlowCompletedEventHandler(object sender, ExoprtToWorkFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExoprtToWorkFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExoprtToWorkFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591